// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmaQ51y2dnnwM1ECIcCkkKJTY5bql0R24',
    appId: '1:967165189772:web:5cbeb113b68c4a716465a9',
    messagingSenderId: '967165189772',
    projectId: 'hotel-booking-vendor-app',
    authDomain: 'hotel-booking-vendor-app.firebaseapp.com',
    storageBucket: 'hotel-booking-vendor-app.appspot.com',
    measurementId: 'G-L1Q6J7RQXG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrZTKIj1LuU2wVO45c3bOgnCGEKWQJ6IU',
    appId: '1:967165189772:android:6a6007c402dbc34d6465a9',
    messagingSenderId: '967165189772',
    projectId: 'hotel-booking-vendor-app',
    storageBucket: 'hotel-booking-vendor-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNx4tCcKs-2SB2Ri9t6ObZmE7gujka4i8',
    appId: '1:967165189772:ios:516a99e39e92c3fe6465a9',
    messagingSenderId: '967165189772',
    projectId: 'hotel-booking-vendor-app',
    storageBucket: 'hotel-booking-vendor-app.appspot.com',
    iosBundleId: 'com.example.hotelBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNx4tCcKs-2SB2Ri9t6ObZmE7gujka4i8',
    appId: '1:967165189772:ios:a743103c977fdb886465a9',
    messagingSenderId: '967165189772',
    projectId: 'hotel-booking-vendor-app',
    storageBucket: 'hotel-booking-vendor-app.appspot.com',
    iosBundleId: 'com.example.hotelBookingApp.RunnerTests',
  );
}
